### ISSUE TITLE
Changes for 2.0

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-attacher#158]
List of items we should do when we're ready for a 2.0:

* Remove deprecated fields
* Revert "revert use patch": #157

/lifecycle frozen

**Comment by jsafrane** [comment]
Filed https://github.com/kubernetes-csi/external-attacher/pull/173 and https://github.com/kubernetes-csi/external-attacher/pull/173

**Comment by jsafrane** [comment]
Both got merged
/close
