### ISSUE TITLE
Vendoring is broken?

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-attacher#166]
Checked out a fresh master branch and ran "make test":
```
### test-vendor:
Repo uses 'dep' for vendoring.
# vendor is out of sync:
github.com/googleapis/gnostic: hash of vendored tree not equal to digest in Gopkg.lock
make: *** [release-tools/build.make:132: test-vendor] Error 1

$ dep version
dep:
 version     : v0.5.1
 build date  : 2019-03-11
 git hash    : faa6189
 go version  : go1.12
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false
```

**Comment by msau42** [comment]
I looked back at the pull jobs for the last merged PR: 
TravisCI uses dep 0.5.1 too and it passed: https://travis-ci.org/kubernetes-csi/external-attacher/builds/569227255?utm_source=github_status&utm_medium=notification
Prow job skipped vendor check because it's dep version is too old :(  https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_external-attacher/165/pull-kubernetes-csi-external-attacher-unit/1159373066078261251

**Comment by msau42** [comment]
cc @pohly

**Comment by pohly** [comment]
Michelle Au <notifications@github.com> writes:
> Checked out a fresh master branch and ran "make test":
>
> ### test-vendor:
> Repo uses 'dep' for vendoring.
> # vendor is out of sync:
> github.com/googleapis/gnostic: hash of vendored tree not equal to digest in Gopkg.lock
> make: *** [release-tools/build.make:132: test-vendor] Error 1

Can you reproduce that reliably?

I saw it once after "git checkout origin/master", but once I tried to
bisect where exactly it failed, it started working also for latest
master (= ea639596f5ab0308d3497e64745e4a4ebd678ca1 in my case).

**Comment by pohly** [comment]
I submitted an enhancement for the vendor check with dep under Prow here: https://github.com/kubernetes-csi/csi-release-tools/pull/27

**Comment by jsafrane** [comment]
The PR from the previous comment was merged, is this issue fixed now?

**Comment by msau42** [comment]
test-vendor is running properly in prow now:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_external-attacher/182/pull-kubernetes-csi-external-attacher-unit/1173926579315675136/build-log.txt

So maybe this is just some problem with my local environment.
/close
