### ISSUE TITLE
deprecated setting `--retry-interval-end`

### ISSUE THREAD

**Issue by hoyho** [kubernetes-csi/external-attacher#171]
[README](https://github.com/kubernetes-csi/external-attacher/blob/master/README.md#important-optional-arguments-that-are-highly-recommended-to-be-used) introduces a deprecated flag  `retry-interval-end`

>--retry-interval-end: The exponential backoff maximum value. See CSI error and timeout handling for details. 5 minutes is used by default.

Seems this flag should have be replaced by `retry-interval-max` as following code from master branch:
```go
retryIntervalMax   = flag.Duration("retry-interval-max", 5*time.Minute, "Maximum retry interval of failed create volume or deletion.")
```

**Comment by jsafrane** [comment]
/assign

The flag is not deprecated, I don't think the attacher ever used `retry-interval-end`. It looks like it's a simple typo.
