### ISSUE TITLE
[investigate] Ensure that if an attach operation times out and plugin successfully attaches it is tracked somewhere

### ISSUE THREAD

**Issue by gnufied** [kubernetes-csi/external-attacher#179]
This is similar to issue we have for mount operation - https://github.com/kubernetes/kubernetes/issues/82190 . I have not investigated this fully if a similar problem exists for external-attacher.

**Comment by jsafrane** [comment]
From the external attacher [readme](https://github.com/kubernetes-csi/external-attacher#csi-error-and-timeout-handling):

> * ControllerPublish: The call might have timed out just before the driver attached a volume and was sending a response. From that reason, timeouts from ControllerPublish is considered as "volume may be attached" or "volume is being attached in the background." The external-attacher will re-try calling ControllerPublish after exponential backoff until it gets either successful response or final (non-timeout) error that the volume cannot be attached.
> * ControllerUnpublish: This is similar to ControllerPublish, The external-attacher will re-try calling ControllerUnpublish with exponential backoff after timeout until it gets either successful response or a final error that the volume cannot be detached.

/close
