### ISSUE TITLE
Delay PublishVolumeRequest until OFFLINE-resizable Volume is resized

### ISSUE THREAD

**Issue by zuzzas** [kubernetes-csi/external-attacher#207]
If a plugin has a `VolumeExpansion.OFFLINE`, then a resize process should happen after `ControllerUnpublishVolume` and before `ControllerPublishVolume`.

Currently, this is not the case, and if I am to delete Pod, then external-resizer and external-attacher would race each other. If external-resizer wins and calls `ControllerPublishVolume` before a resize operation is finished, then we have to delete a Pod again. Which is incredibly frustrating.

I've hacked together a hacky "solution". But I think that OFFLINE resize should work properly on the CSI side, not on the plugin side.

I propose not Publishing a Volume to a Node if a PVC is currently resizing.

**Comment by zuzzas** [comment]
Here is the hack:
1. Lock volume if there is a resize operation pending: https://github.com/flant/yandex-csi-driver/blob/master/driver/controller.go#L559
2. Refuse to `ControllerPublishVolume` if it is locked: https://github.com/flant/yandex-csi-driver/blob/master/driver/controller.go#L270-L272
3. Unlock volume if it is resized: https://github.com/flant/yandex-csi-driver/blob/master/driver/controller.go#L564

**Comment by jsafrane** [comment]
I think this should be solved on the driver level.

Kubernetes is a dynamic system and does not offer any mechanism to "lock" objects on controller level and clean up the locks when a controller dies / restarts.

**Comment by zuzzas** [comment]
Oh, but there are examples of locking throughout the Kubernetes. Leases (and Endpoints previously) that are used for leader election is a good example.

**Comment by jsafrane** [comment]
Leader election works per controller (i.e. one object per cluster). You want to have a lock per PV. That's completely different scale.

We tried to add annotation with a lock to PVCs to be able to run multiple provisioners in parallel, but adding/removing/checking the annotation on every PVC basically overloaded API server.
See https://github.com/kubernetes-incubator/external-storage/pull/892, https://github.com/kubernetes-csi/external-provisioner/issues/68, https://github.com/kubernetes-incubator/external-storage/pull/553. It does not scale.

**Comment by zuzzas** [comment]
Okay, I see, thanks for the references.

Let's approach the issue from another direction. Has there been a successful CSI `OFFLINE` ExpandVolume which does not suffer from issues that I've outlined on the top? Because I am not sure how that can be fixed on the driver side, if the driver is not aware (when Publishing Volume) that there is a resize pending.
