### ISSUE TITLE
Incorrect repository layour for v2 Go Modules

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/external-attacher#208]
From https://github.com/kubernetes-csi/external-snapshotter/issues/239:
```
$ go get -v github.com/kubernetes-csi/external-attacher@v2.1.0
go get github.com/kubernetes-csi/external-attacher@v2.1.0: github.com/kubernetes-csi/external-attacher@v2.1.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

See https://github.com/kubernetes-csi/external-snapshotter/pull/240 for a fix.

**Comment by alex1989hu** [comment]
Do you need `dep` compatibility with all of its side effect (e.g. symlink creation in `v2` directory)?

**Comment by alex1989hu** [comment]
To verify: https://sum.golang.org/lookup/github.com/kubernetes-csi/external-attacher/v2@v2.1.1

**Example go.mod**
```
 module github.com/foo/bar

 go 1.13

 require (
     github.com/kubernetes-csi/external-attacher/v2 v2.1.1
 )
```
Import statements have to be updated to use it correctly:

```go
package main

import (
	"github.com/kubernetes-csi/external-attacher/v2/pkg/controller"
)

// Your code here

```
