### ISSUE TITLE
Bump version to 3.0.0

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/external-attacher#212]
If #200 is merged, it introduced RBAC change that needs major version bump of the attacher to v3.0.0. And therefore we need to bump also attacher's go module to v3, similarly to #209 before release.

**Comment by pohly** [comment]
/remove-lifecycle stale

@xing-yang : would it be possible to to a v3.0.0-alpha1 of external-snapshotter?

I need to import a recent release of external-snapshotter with support for client-go >= 1.18 into external-provisioner for the storage capacity work, see https://github.com/kubernetes-csi/external-provisioner/pull/450

I could just import master, but that's sub-optimal.

**Comment by jsafrane** [comment]
@pohly, this is external-attacher, not snapshotter. Are you sure you need external-attacher 3.0.0-alpha? People usually don't import this repo.

**Comment by pohly** [comment]
Right, I mixed up snapshotter and attacher.

**Comment by jsafrane** [comment]
/close
3.0 has been released a while ago
