### ISSUE TITLE
Stale mounts are left if pod is deleted before nodePublish is completed

### ISSUE THREAD

**Issue by raunakkumar** [kubernetes-csi/external-attacher#216]
When a pod is deleted before nodePublish is done, but after nodeStage is done, it will not be unmounted by kubelet. This causes stale mounts on host to be left around.

**Comment by msau42** [comment]
Please open an issue in kubernetes/kubernetes and tag sig storage.

**Comment by raunakkumar** [comment]
Associated with issue https://github.com/kubernetes/kubernetes/issues/89112

**Comment by msau42** [comment]
Thanks, closing this one as this is not the component handling nodepublish
/close
