### ISSUE TITLE
Remove simple attacher mode

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-attacher#226]
Before we had skip attach feature, drivers were required to run external attacher, which has a simple mode to always set attached without calling the driver. 

Now that the skip attach feature is GA, there is no need to run the sidecar anymore, so this logic can be removed.

Next major version bump would probably be a good time to do this

**Comment by jsafrane** [comment]
/lifecycle frozen

This needs to wait until https://github.com/kubernetes/kubernetes/issues/89173 is fixed

**Comment by jsafrane** [comment]
@humblec I remember you did some crazy stuff with your CSI drivers that don't really support ControllerPublish. Do you actually implement a dummy ControllerPublish in your driver and run a real external-attacher or you just run the external-attacher in the dummy mode?

**Comment by humblec** [comment]
> @humblec I remember you did some crazy stuff with your CSI drivers that don't really support ControllerPublish.

@jsafrane unfortunately true that we did something which does not really fall into the CSI expectation. :(

>Do you actually implement a dummy ControllerPublish in your driver and run a real external-attacher or you just run the external-attacher in the dummy mode?

latter, ie we run external-attacher in the dummy mode.  The RPC is declared as `unimplemented`.

**Comment by jsafrane** [comment]
@humblec would it be possible for you to write a dummy ControllerPublish, so we can remove the dummy attacher mode?

**Comment by jsafrane** [comment]
@humble I can still see that the Ceph CSI drivers need the dummy attacher. Is there any plan to continue with the effort?

@msau42 if we take Ceph CSI as an example of a CSI driver that still needs the dummy attacher, does it make sense to remove it from the external-attacher? We don't know how many CSI drivers are out there that need it and it's quite small amount of code that has just worked for years.

**Comment by msau42** [comment]
There was a recent slack discussion where it looks like there is still a use case for the dummy attacher in order to enforce RWO.
