### ISSUE TITLE
External-attacher fails to delete after losing leader election lease

### ISSUE THREAD

**Issue by RaunakShah** [kubernetes-csi/external-attacher#233]
My cluster is in a state where the external-attacher has lost its lease to be leader but is still in the "Running" phase. 

I see the following logs at start up in external-attacher:

```
I0602 00:08:15.460799       1 main.go:91] Version: v1.1.1
I0602 00:08:15.461641       1 connection.go:151] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
I0602 00:08:16.462740       1 common.go:111] Probing CSI driver for readiness
I0602 00:08:16.465857       1 main.go:141] CSI driver name: "csi.vsphere.vmware.com"
I0602 00:08:16.467440       1 main.go:165] CSI driver supports ControllerPublishUnpublish, using real CSI handler
I0602 00:08:16.467633       1 leaderelection.go:217] attempting to acquire leader lease  kube-system/external-attacher-leader-csi-vsphere-vmware-com...
I0602 00:08:16.476535       1 leaderelection.go:227] successfully acquired lease kube-system/external-attacher-leader-csi-vsphere-vmware-com
I0602 00:08:16.476637       1 leader_election.go:172] new leader detected, current leader: 423404be3294a7d8e40ece6c91d26d83
I0602 00:08:16.476668       1 leader_election.go:165] became leader, starting
I0602 00:08:16.476707       1 controller.go:113] Starting CSI attacher
...
```

This cluster has been used at scale, so my attacher logs span ~ 300k lines. 
Everything is working smoothly until:

```
...
I0602 15:58:17.620560       1 controller.go:205] Started PV processing "pvc-d333c439-e2fe-4497-a83e-61bf4bab2073"
I0602 15:58:17.620566       1 csi_handler.go:412] CSIHandler: processing PV "pvc-d333c439-e2fe-4497-a83e-61bf4bab2073"
I0602 15:58:17.620575       1 csi_handler.go:416] CSIHandler: processing PV "pvc-d333c439-e2fe-4497-a83e-61bf4bab2073": no deletion timestamp, ignoring
I0602 15:58:17.614597       1 controller.go:205] Started PV processing "pvc-4f481107-3520-405e-b6cd-2e9b12e68d9e"
I0602 15:58:17.621013       1 csi_handler.go:412] CSIHandler: processing PV "pvc-4f481107-3520-405e-b6cd-2e9b12e68d9e"
I0602 15:58:17.621028       1 csi_handler.go:416] CSIHandler: processing PV "pvc-4f481107-3520-405e-b6cd-2e9b12e68d9e": no deletion timestamp, ignoring
I0602 15:58:58.785178       1 reflector.go:370] k8s.io/client-go/informers/factory.go:133: Watch close - *v1.PersistentVolume total 0 items received
I0602 16:00:44.551304       1 leaderelection.go:263] failed to renew lease kube-system/external-attacher-leader-csi-vsphere-vmware-com: failed to tryAcquireOrRenew context deadline exceeded
F0602 16:00:44.551360       1 leader_election.go:169] stopped leading
I0602 16:00:44.735079       1 controller.go:126] Shutting CSI attacher
```

Post this timestamp, any attempt to attach volume by creating a Pod fails with this error: 

```
  Warning  FailedAttachVolume  2m10s      attachdetach-controller  AttachVolume.Attach failed for volume "pvc-57496b43-5e76-49cc-8ceb-f8ff4b8099b0" : attachdetachment timeout for volume 8a78689a-4e80-422d-bfaa-7c599b6b72bd
```

I looked in kube-controller-manager logs and see that for these pods attach starts for the volume: 

```
I0606 01:05:56.590656       1 reconciler.go:288] attacherDetacher.AttachVolume started for volume "pvc-57496b43-5e76-49cc-8ceb-f8ff4b8099b0" (UniqueName: "kubernetes.io/csi/csi.vsphere.vmware.com^2dfaa11c-8526-4682-b5b8-60ebaf720c5a") from node "<node-name>"
```

And the corresponding volumeattachment is created on the API server:

```
# kubectl get volumeattachment | grep pvc-57496b43-5e76-49cc-8ceb-f8ff4b8099b0
csi-58895acb6815e5b21b008b36e5d29d2ee3e442d6ddf5f8d215740d51349f142a   csi.vsphere.vmware.com   pvc-57496b43-5e76-49cc-8ceb-f8ff4b8099b0   <node-name>   false      14s
```

However this call eventually times out:
```
I0606 01:07:56.707005       1 event.go:281] Event(v1.ObjectReference{Kind:"Pod", Namespace:"<namespace>", Name:"<name>", UID:"93b62bfa-fd1c-47a8-82b1-8e9792626870", APIVersion:"v1", ResourceVersion:"4033080", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' AttachVolume.Attach failed for volume "pvc-57496b43-5e76-49cc-8ceb-f8ff4b8099b0" : attachdetachment timeout for volume 2dfaa11c-8526-4682-b5b8-60ebaf720c5a
```

Then kubernetes deletes the volumeattachment and goes through the same cycle (we have an operator that keeps trying to recreate the Pod). 

My expectation is that when external-attacher loses its lease, it should restart the container. 
Funnily enough, when i manually tried to delete my csi-controller Pod, it stuck in the Terminating state like below: 

```
# kubectl get pod -A | grep Ter
kube-system                               vsphere-csi-controller-5484f9bbc8-znbht                           1/6     Terminating        23         4d2h
```

However since this process did create a new csi-controller Pod, my subsequent attach/detach operations succeeded and my cluster is back to its expected state. 

My expectation is that on losing leader status, the attacher container should Terminate and restart. It seems to be stuck in the Running phase even though its says "Shutting CSI attacher". This expectation is based on the behavior i've seen with external-provisioner and resizer. 

More info:
Kubernetes version: 1.17.4
CSI driver: vsphere-csi-driver v2.0.0
External-attacher version: v1.1.1

**Comment by RaunakShah** [comment]
Also, when i look at the new attacher logs, i see this:

```
I0606 02:18:16.349269       1 main.go:91] Version: v1.1.1
I0606 02:18:16.357933       1 connection.go:151] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
I0606 02:18:19.293775       1 common.go:111] Probing CSI driver for readiness
I0606 02:18:19.295852       1 main.go:141] CSI driver name: "csi.vsphere.vmware.com"
I0606 02:18:19.321005       1 main.go:165] CSI driver supports ControllerPublishUnpublish, using real CSI handler
I0606 02:18:19.342945       1 leaderelection.go:217] attempting to acquire leader lease  kube-system/external-attacher-leader-csi-vsphere-vmware-com...
I0606 02:18:19.406846       1 leaderelection.go:326] lock is held by 423404be3294a7d8e40ece6c91d26d83 and has not yet expired
I0606 02:18:19.406890       1 leaderelection.go:222] failed to acquire lease kube-system/external-attacher-leader-csi-vsphere-vmware-com
I0606 02:18:19.406916       1 leader_election.go:172] new leader detected, current leader: 423404be3294a7d8e40ece6c91d26d83
I0606 02:18:28.069874       1 leaderelection.go:326] lock is held by 423404be3294a7d8e40ece6c91d26d83 and has not yet expired
I0606 02:18:28.069911       1 leaderelection.go:222] failed to acquire lease kube-system/external-attacher-leader-csi-vsphere-vmware-com
I0606 02:18:38.797922       1 leaderelection.go:227] successfully acquired lease kube-system/external-attacher-leader-csi-vsphere-vmware-com
I0606 02:18:38.798012       1 leader_election.go:172] new leader detected, current leader: 4234a11414b63470afc1acdfb34a95c0
```

Looks like the old node (423404be3294a7d8e40ece6c91d26d83) was still the leader even though its been 4 days since it said "stopped leading", before this instance became leader and my cluster state was restored.

**Comment by jsafrane** [comment]
@RaunakShah, the controller *should* exit & be restarted by Kubernetes. Looking at the code, `"stopped leading"` is printed this way:

https://github.com/kubernetes-csi/external-attacher/blob/4b601b90c92af49e1f146ff52be0e8042651ef47/vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go#L169

And `klog.Fatal` documentation (and its code) say
> `Fatal logs to the FATAL, ERROR, WARNING, and INFO logs, including a stack trace of all running goroutines, then calls os.Exit(255).`

From some reason, `os.Exit()` did not work.

> Funnily enough, when i manually tried to delete my csi-controller Pod, it stuck in the Terminating state like below:

That's very interesting. Do you have kubelet logs from that time? Can you check why the pod did not die and what was blocking it?

**Comment by jsafrane** [comment]
Looking at the code, this message is printed just before `os.Exit(255)`: `stopped leading`. Why it did not exit then? And why is the pod Terminating and not deleted? Can you reproduce the bug? Do you have kubelet / container runtime logs from the time when it happened so we can check what went wrong with the pod?

**Comment by RaunakShah** [comment]
@jsafrane unfortunately i wasn't able to capture kubelet logs, only kube-controller-manager which doesn't have any useful information. Its not consistently reproducible, but we have found it a couple of times in the past. I'll make sure to collect kubelet logs if its seen again.

> And why is the pod Terminating and not deleted?

The container was still in the "Running" state. I did some more digging and found that docker still thought the container was running:

```
root@423404be3294a7d8e40ece6c91d26d83 [ ~ ]# docker ps | grep attach
b6d7cc2176a3        7841e1650cb1          "/csi-attacher --v=4…"   5 days ago          Up 5 days                               k8s_csi-attacher_vsphere-csi-controller-5484f9bbc8-znbht_kube-system_9e0d0a2b-ab79-4a42-b53e-44b878d13b3d_0
```

But i couldnt find a PID from docker top!

```
root@423404be3294a7d8e40ece6c91d26d83 [ ~ ]# docker top b6d7cc2176a3
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root@423404be3294a7d8e40ece6c91d26d83 [ ~ ]#
```

I'm not sure if this counts as a Kubernetes/attacher issue or docker..
