### ISSUE TITLE
Separate k8 clients for leader election and attacher

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-attacher#241]
We don't want api throttling due to heavy volume activity to also throttle leader election, so it would be good to have different k8s clients for them. We've already made the change in provisioner and resizer. It would be good to make for the remaining sidecars.

cc @xing-yang @jsafrane

**Comment by xing-yang** [comment]
@msau42 do you also want to have configurable QPS and Burst for k8s clients in the external-attacher?

**Comment by xing-yang** [comment]
CC @RaunakShah

**Comment by msau42** [comment]
I think we can leave configurable qps and burst until we have time to do more performance experiments.

**Comment by xing-yang** [comment]
Sounds good.

**Comment by jsafrane** [comment]
See https://github.com/kubernetes-csi/external-attacher/pull/242
