### ISSUE TITLE
Is reconciling only available for in-Tree drivers?

### ISSUE THREAD

**Issue by david-enli** [kubernetes-csi/external-attacher#243]
Hello, After enabling `csi.ControllerServiceCapability_RPC_LIST_VOLUMES_PUBLISHED_NODES` in controllerserver and including the PublishedNodeIDs field in the ListVolumes response. We started to see the following log message from the csi-attacher sidecar. And I found the following function called as part of the reconciling code from the sidecar:

```
// RepairVolumeHandle generates a correct volume handle based on node ID information.
func (CSITranslator) RepairVolumeHandle(driverName, volumeHandle, nodeID string) (string, error) {
	if plugin, ok := inTreePlugins[driverName]; ok {
		return plugin.RepairVolumeHandle(volumeHandle, nodeID)
	}
	return "", fmt.Errorf("could not find In-Tree driver name for CSI plugin %v", driverName)
}
```
is reconciling not supported for non in-tree CSI drivers? thanks in Advance for your help

**Comment by msau42** [comment]
/kind bug
That sounds like a bug. If a driver doesn't suppose csi migration, we should not call repairvolumehandle.

**Comment by david-enli** [comment]
I'm so sorry, forgot to include the log message:
`W0729 13:59:06.131593       1 csi_handler.go:159] Failed to repair volume handle  for driver pure-csi: could not find In-Tree driver name for CSI plugin pure-csi`

**Comment by msau42** [comment]
@yuga711 is going to work on a fix
