### ISSUE TITLE
Multi-arch image support

### ISSUE THREAD

**Issue by jsrz** [kubernetes-csi/external-attacher#266]
Hello,

Would like to put in a request for support of multi-arch images (Arm). Current external-attacher images only support x86.
I verified that I can easily build binaries and docker images manually, so I'd imagine it shouldn't take too much effort to support this.

**Comment by jsafrane** [comment]
I am not familiar with our image building, but according to https://github.com/kubernetes-csi/external-attacher/pull/261 we do have arm64 image. 

Is `docker pull k8s.gcr.io/sig-storage/csi-attacher:v3.0.0` not working?

**Comment by jsrz** [comment]
Hello,

That image pull appears to work and run. It errors on config, which is fine, as long as there is no exec format error I think it's good.

However, you seem to be hosting from a different location than what I'm using.

I'm running rook (https://rook.io). It seems to source images from quay:
quay.io/k8scsi/csi-attacher:v2.1.0

I can try pointing to images on k8s.gcr.io instead of quay.io, but now I'm confused as to why these images are hosted on quay (assuming k8s.gcr works for me)?

**Comment by jsafrane** [comment]
We've moved from quay.io/k8scsi to gcr.io exactly to enable multiarch images.

**Comment by jsrz** [comment]
I see, so perhaps it's just a matter of waiting on rook to switch their default images over to gcr.io. Got it.

Thanks! Closing

**Comment by themonaminor** [comment]
k8s.gcr.io/sig-storage/csi-attacher:v3.0.0  is this image is compatible on windows nodes?

**Comment by pohly** [comment]
> k8s.gcr.io/sig-storage/csi-attacher:v3.0.0 is this image is compatible on windows nodes?

No. Only node-driver-registrar has Windows support: https://github.com/kubernetes-csi/node-driver-registrar/blob/master/Dockerfile.Windows
