### ISSUE TITLE
external-attacher should not decide default filesystem type

### ISSUE THREAD

**Issue by michael-db** [kubernetes-csi/external-attacher#287]
When filesystem type (FSType) is empty, the csi-attacher sidecar changes it to "ext4" before calling the CSI driver's ControllerPublishVolume().

It should not. While the default for many types of volume is "ext4", no default is specified for a CSI volume, and that is correct: it is the particular CSI driver that must decide what the default filesystem is when none is specified, not the sidecar container.

There appears to be no simple workaround: a driver using external-attacher has no way of knowing whether the "ext4" it sees in a ControllerPublishVolume is there because it was specifically requested or because the csi-attacher has exceeded its authority.

Therefore remove `defaultFSType` and the associated code from external-attacher.

After this fix, some existing CSI drivers may need to change to preserve their existing response to a PVC with an unspecified filesystem. If that is a significant concern then consider replacing defaultFSType with a command-line argument with a default value of "ext4" but which can at least be set to "" to disable the current interference. However, simple removal of defaultFSType is the preferable fix.

/kind bug

**Comment by msau42** [comment]
Agree, I think external-attacher should just use whatever fstype is set on in the pv object. Maybe introduce a cmd line argument similar to external-provisioner for backwards compatibility. @jsafrane wdyt?

/remove-lifecycle stale

**Comment by jsafrane** [comment]
Yes, a new argument to turn off the autodetection would be the best, potentially deprecating the old behavior and removing it in a future release.
