### ISSUE TITLE
ControllerPublishVolume called frequently after attached

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-attacher#291]
We're seeing ControllerPublishVolume being called very frequently on already attached volumes. This is skewing our metrics and hiding errors because we see the majority of ControllerPublishVolume calls succeed < 1 second. The frequency seems to match with the frequency of ListVolumes, so I suspect it's related to the reconciler there.

/kind bug

cc @Jiawei0227 @chrishenzie

**Comment by Jiawei0227** [comment]
On a side note, since we have volume_operation_duration_seconds to record PV provision/delete e2e time. We could also record attach/detach e2e metric to it using VolumeAttachment object

**Comment by divyenpatel** [comment]
@msau42 we are also seeing `ControllerUnpublishVolume` called twice for the same volume. We have not implemented ListVolumes in the vSphere CSI Driver.



Time Stamp: 2021-02-28T19:04:12.439965592Z

> {"log":"{\"level\":\"info\",\"time\":\"2021-02-28T19:04:12.439965592Z\",\"caller\":\"vanilla/controller.go:732\",\"msg\":\"ControllerUnpublishVolume: called with args {VolumeId:13919647-99f2-4033-990d-947dd79e34e2 NodeId:172.50.176.255 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}\",\"TraceId\":\"9667cf07-26de-403e-9a9f-61fac3b0f2ea\"}\n","stream":"stderr","time":"2021-02-28T19:04:12.440078303Z"}
{"log":"{\"level\":\"info\",\"time\":\"2021-02-28T19:04:12.995041397Z\",\"caller\":\"volume/manager.go:431\",\"msg\":\"DetachVolume: volumeID: \\\"13919647-99f2-4033-990d-947dd79e34e2\\\", vm: \\\"VirtualMachine:vm-754 [VirtualCenterHost: 10.198.160.103, UUID: 420b76f0-8169-8a95-0744-ce7b0d066ed7, Datacenter: Datacenter [Datacenter: Datacenter:datacenter-63, VirtualCenterHost: 10.198.160.103]]\\\", opId: \\\"8e072e41\\\"\",\"TraceId\":\"9667cf07-26de-403e-9a9f-61fac3b0f2ea\"}\n","stream":"stderr","time":"2021-02-28T19:04:12.995264528Z"}
{"log":"{\"level\":\"info\",\"time\":\"2021-02-28T19:04:12.995151613Z\",\"caller\":\"volume/manager.go:461\",\"msg\":\"DetachVolume: Volume detached successfully. volumeID: \\\"13919647-99f2-4033-990d-947dd79e34e2\\\", vm: \\\"8e072e41\\\", opId: \\\"VirtualMachine:vm-754 [VirtualCenterHost: 10.198.160.103, UUID: 420b76f0-8169-8a95-0744-ce7b0d066ed7, Datacenter: Datacenter [Datacenter: Datacenter:datacenter-63, VirtualCenterHost: 10.198.160.103]]\\\"\",\"TraceId\":\"9667cf07-26de-403e-9a9f-61fac3b0f2ea\"}\n","stream":"stderr","time":"2021-02-28T19:04:12.995308813Z"}

Time Stamp: 2021-02-28T19:04:13.006772717Z

> {"log":"{\"level\":\"info\",\"time\":\"2021-02-28T19:04:13.006772717Z\",\"caller\":\"vanilla/controller.go:732\",\"msg\":\"ControllerUnpublishVolume: called with args {VolumeId:13919647-99f2-4033-990d-947dd79e34e2 NodeId:172.50.176.255 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}\",\"TraceId\":\"0257970c-9a77-4e5e-b9d7-9ffb9cfd7d4a\"}\n","stream":"stderr","time":"2021-02-28T19:04:13.006868628Z"}
{"log":"{\"level\":\"info\",\"time\":\"2021-02-28T19:04:13.66006303Z\",\"caller\":\"volume/manager.go:431\",\"msg\":\"DetachVolume: volumeID: \\\"13919647-99f2-4033-990d-947dd79e34e2\\\", vm: \\\"VirtualMachine:vm-754 [VirtualCenterHost: 10.198.160.103, UUID: 420b76f0-8169-8a95-0744-ce7b0d066ed7, Datacenter: Datacenter [Datacenter: Datacenter:datacenter-63, VirtualCenterHost: 10.198.160.103]]\\\", opId: \\\"8e072e43\\\"\",\"TraceId\":\"0257970c-9a77-4e5e-b9d7-9ffb9cfd7d4a\"}\n","stream":"stderr","time":"2021-02-28T19:04:13.660613058Z"}
{"log":"{\"level\":\"info\",\"time\":\"2021-02-28T19:04:13.665936454Z\",\"caller\":\"volume/manager.go:452\",\"msg\":\"DetachVolume: volumeID: \\\"13919647-99f2-4033-990d-947dd79e34e2\\\" not found on vm: VirtualMachine:vm-754 [VirtualCenterHost: 10.198.160.103, UUID: 420b76f0-8169-8a95-0744-ce7b0d066ed7, Datacenter: Datacenter [Datacenter: Datacenter:datacenter-63, VirtualCenterHost: 10.198.160.103]]. Assuming volume is already detached\",\"TraceId\":\"0257970c-9a77-4e5e-b9d7-9ffb9cfd7d4a\"}\n","stream":"stderr","time":"2021-02-28T19:04:13.666144863Z"}

**Comment by hem2** [comment]
@divyenpatel Were you able to fix it? We're seeing it occasionally too.

**Comment by divyenpatel** [comment]
@hem2 no we are seeing this issue with latest external-attacher sidecar as well sometime.

@leiyiz how https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/813 is helping fix the reported issue?

**Comment by leiyiz** [comment]
the cause of the issue we were seeing (frequent `ControllerPublishVolume` calls) were due to regional PD disks not listed out when the external-attacher tries to determine the attached status of volumes.

> called twice for the same volume

this issue I think might be different if the ListVolume is not implemented.
