### ISSUE TITLE
csi-attacher:v3.1.0 image having VA issues

### ISSUE THREAD

**Issue by arahamad** [kubernetes-csi/external-attacher#307]
following is the VA issues in csi-attacher:v3.1.0 image

Vulnerable Packages Found
=========================

Vulnerability ID   Policy Status   Affected Packages   How to Resolve   
DLA-2542-1         Active          tzdata              Upgrade tzdata to >= 2021a-0+deb9u1   
DLA-2509-1         Active          tzdata              Upgrade tzdata to >= 2021a-0+deb9u1

**Comment by Kartik494** [comment]
Hi @arahamad Could you explain more on issue you facing while using `csi-attacher:v3.1.0`  image

**Comment by cornfeedhobo** [comment]
@arahamad you posted an error about a debian system. That isn't about this repo.
