### ISSUE TITLE
csi-attacher:v3.3.0 image unavailable

### ISSUE THREAD

**Issue by pawcykca** [kubernetes-csi/external-attacher#326]
Image from latest release v3.3.0 is not available in 'k8s.gcr.io' registry:
`docker pull k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
Error response from daemon: manifest for k8s.gcr.io/sig-storage/csi-attacher:v3.3.0 not found: manifest unknown: Failed to fetch "v3.3.0" from request "/v2/sig-storage/csi-attacher/manifests/v3.3.0".`

**Comment by pohly** [comment]
Images are no longer published on k8s.gcr.io. The new location is k8s.gcr.io/sig-storage/csi-attacher

**Comment by msau42** [comment]
The url looks correct. I think the issue is it takes some time for us to manually promote the image after cutting the tag.

https://github.com/kubernetes/k8s.io/pull/2531 should fix it.

**Comment by pawcykca** [comment]
@msau42 Yes, it's working now - thanks!
