### ISSUE TITLE
Attachment reconciler is incorrectly using nodeid annotation

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-attacher#332]
The nodeid annotation has been deprecated and removed for a few releases now. This logic is probably not working:
https://github.com/kubernetes-csi/external-attacher/blob/c4cfca3cd22d7437f0a1d712e3fac30211d6ec09/pkg/controller/csi_handler.go#L137

It should be using this instead:
https://github.com/kubernetes-csi/external-attacher/blob/c4cfca3cd22d7437f0a1d712e3fac30211d6ec09/pkg/controller/csi_handler.go#L732

**Comment by jsafrane** [comment]
@msau42, the change you suggested is good to have, still, the annotation is needed to detach volumes from machines that don't have CSINode - for example when they were deleted. I think the logic in `getNodeID` still works and the annotation was not removed from VolumeAttachment: https://github.com/kubernetes-csi/external-attacher/blob/631c3aa70e825c77805753bb776333239ea9ade9/pkg/controller/csi_handler.go#L322-L323

**Comment by msau42** [comment]
Thanks, I confused it with the nodeid annotation on Node objects. Maybe adding a comment describing that scenario would be helpful.
