### ISSUE TITLE
csi-attacher:v3.4.0 image unavailable

### ISSUE THREAD

**Issue by tomaso** [kubernetes-csi/external-attacher#341]
This is similar issue to #326 - there is already a v3.4.0 tag visible at https://api.github.com/repos/kubernetes-csi/external-attacher/releases/latest
but it is not possible to pull the image from k8s.gcr.io/sig-storage/csi-attacher:v3.4.0

**Comment by jsafrane** [comment]
This was fixed by https://github.com/kubernetes/k8s.io/pull/3225
