### ISSUE TITLE
csi attacher report panic in log

### ISSUE THREAD

**Issue by Kvasscn** [kubernetes-csi/external-attacher#377]
csi-attacher  seems  crash  in my test environment,  Does anyone know why？
The  error log:
I0920 17:27:33.094181  116997 csi_handler.go:216] CSIHandler: processing VA "csi-6958c8b9eeaf1a5015f350513238627af0e0268a7d2e59cb1515dbdb8badfb69"
I0920 17:27:33.094185  116997 csi_handler.go:216] CSIHandler: processing VA "csi-6a596806520026f086db41af9279ff79e385f73ed8a7f5eb6b06bffa2913d6c9"
I0920 17:27:33.094192  116997 csi_handler.go:238] "csi-6958c8b9eeaf1a5015f350513238627af0e0268a7d2e59cb1515dbdb8badfb69" is already attached
I0920 17:27:33.094196  116997 csi_handler.go:238] "csi-6a596806520026f086db41af9279ff79e385f73ed8a7f5eb6b06bffa2913d6c9" is already attached
I0920 17:27:33.094202  116997 csi_handler.go:232] CSIHandler: finished processing "csi-6958c8b9eeaf1a5015f350513238627af0e0268a7d2e59cb1515dbdb8badfb69"
I0920 17:27:33.094208  116997 csi_handler.go:232] CSIHandler: finished processing "csi-6a596806520026f086db41af9279ff79e385f73ed8a7f5eb6b06bffa2913d6c9"
I0920 17:27:33.093943  116997 controller.go:198] Started VA processing "csi-ee859c16412daad247216fc55a385a9e37b4ab553e62c3745123fcd34a7fe1ac"
I0920 17:27:33.094240  116997 csi_handler.go:216] CSIHandler: processing VA "csi-ee859c16412daad247216fc55a385a9e37b4ab553e62c3745123fcd34a7fe1ac"
I0920 17:27:33.094256  116997 csi_handler.go:238] "csi-ee859c16412daad247216fc55a385a9e37b4ab553e62c3745123fcd34a7fe1ac" is already attached
E0920 17:27:33.094187  116997 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x164a680), concrete:(*runtime._type)(0x16fd0e0), asserted:(*runtime._type)(0x184d9c0), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.VolumeAttachment)
goroutine 145 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x168f240, 0xc00080a030)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x168f240, 0xc00080a030)
	/home/travis/.gimme/versions/go1.15.linux.amd64/src/runtime/panic.go:969 +0x175
github.com/kubernetes-csi/external-attacher/pkg/controller.(*CSIAttachController).vaDeleted(0xc000034c80, 0x16fd0e0, 0xc000b0d640)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/pkg/controller/controller.go:164 +0xa6
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/client-go/tools/cache/controller.go:245
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/client-go/tools/cache/shared_informer.go:779 +0x166
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000503f60)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0000fff60, 0x1a3ade0, 0xc00069a030, 0x164b501, 0xc000698060)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000503f60, 0x3b9aca00, 0x0, 0x1, 0xc000698060)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000176580)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000357720, 0xc00069c000)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.VolumeAttachment [recovered]
	panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.VolumeAttachment

goroutine 145 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x168f240, 0xc00080a030)
	/home/travis/.gimme/versions/go1.15.linux.amd64/src/runtime/panic.go:969 +0x175
github.com/kubernetes-csi/external-attacher/pkg/controller.(*CSIAttachController).vaDeleted(0xc000034c80, 0x16fd0e0, 0xc000b0d640)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/pkg/controller/controller.go:164 +0xa6
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/client-go/tools/cache/controller.go:245
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/client-go/tools/cache/shared_informer.go:779 +0x166
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000503f60)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000695f60, 0x1a3ade0, 0xc00069a030, 0x164b501, 0xc000698060)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000503f60, 0x3b9aca00, 0x0, 0x1, 0xc000698060)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000176580)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000357720, 0xc00069c000)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/travis/gopath/src/github.com/kubernetes-csi/external-attacher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65

**Comment by Kartik494** [comment]
@Kvasscn may i know on which kubernetes version you are testing it and version of attacher also?
