### ISSUE TITLE
VolumeAttachment has attached status true but actual state false

### ISSUE THREAD

**Issue by Payback159** [kubernetes-csi/external-attacher#416]
**What happened**:

Hello, in the wake of the discussion in this Issue https://github.com/kubernetes/cloud-provider-openstack/issues/2137
I am also creating a request here.

csi-attacher in csi-cinder-controllerplugin logs several VolumeAttachments with the message that the attached status is true but actual state is false.

I have tried to understand which 2 states are being compared here but with my current understanding this log entry should not come up. At the moment we are using csi-attacher v3.3.0

example:

```bash
csi-cinder-controllerplugin-76c485697b-984tc csi-attacher W0228 09:29:56.252060       1 csi_handler.go:186] VA csi-18d7a5e4ba40c759559d5ea42ae029eb21cc1eac39b6323941749a500a198325 for volume d2268cd2-3b8e-43b0-ae5e-b8cde0673d34 has attached status true but actual state false. Adding back to VA queue for forced reprocessing
```

Can someone please explain to me exactly which 2 states are being compared here? From my point of view the first attached state value should come from `kubectl get volumeattachments csi-18d7a5e4ba40c759559d5ea42ae029eb21cc1eac39b6323941749a500a198325`. But where exactly does the 2nd value come from, the `false` value?

**What you expected to happen**:

Like other clusters with the same component combination, the log entry should not show up at all.

**Comment by jsafrane** [comment]
`VA %s for volume %s has attached status %v but actual state %v` comes from periodic sync of VolumeAttachment objects ("attached status") with result of `ListVolumes()` CSI call ("actual state"). It tries to attach volumes that were detached outside of the external-attacher, e.g. by a user. Or, on some clouds, a part of the cloud that's responsible for `ListVolumes()` CSI call does not have the information that corresponding `ControllerPublishVolume()` has succeeded (their "eventual consistency" pattern). Or there is a bug in the CSI driver or the attacher, of couse.

**Comment by Payback159** [comment]
Hi @jsafrane,

thank you for your answer. 2 questions arise there with me.

* If I understand you correctly, the log entry should disappear if I remount the PersistentVolume once. The attachment should now come from the CSI driver and the necessary event/information should be available or?
* So to know where the information from the ListVolumes comes from I would have to check where the concrete CSI implementation gets the values from or?

**Comment by jelinek-wgs** [comment]
Hello @jsafrane,

The logs seem to occur when a PVC exists that has been mounted once in the past and then the pod is shut down (e.g. for autoscaling). As soon as you clean up the unused PVCs the log entry disappears.

So the log entry makes sense again, because an unused PVC has of course the status "attached: false". I would argue that this is actually unclean and an unused / unmounted PVC/PV should not show up in the logs.

How do you see it?

Thanks again for your support!

**Comment by Payback159** [comment]
Hello @jsafrane,

The logs seem to occur when a PVC exists that has been mounted once in the past and then the pod is shut down (e.g. for autoscaling). As soon as you clean up the unused PVCs the log entry disappears.

So the log entry makes sense again, because an unused PVC has of course the status "attached: false". I would argue that this is actually unclean and an unused / unmounted PVC/PV should not show up in the logs.

How do you see it?

Thanks again for your support!

**Comment by jsafrane** [comment]
If you see `volume XYZ has attached status true but actual state false`, then VolumeAttachment.status.attached is `true`. Where do you see it as `attached: false`?

**Comment by vhurtevent** [comment]
Hello @Payback159,

we are facing the same problem (Kube+Cinder/OpenStack), and the CSI Cinder logs are full of these messages and attaching/detaching volumes are longer and longer.

Do you find any solution ?

**Comment by Payback159** [comment]
Hello @vhurtevent,

apparently the log entries occur when you have PVC's in the cluster that were mounted once in the past and then left and never cleaned up. In our case it was PVC's coming from multiple statefulsets scaled via horizontal pod autoscaler.

We were able to "remove" the logs by cleaning up the leftover PVCs.

However, since in our case they were not the cause of our problem at the time, we stopped further analysis of these log entries.

**Comment by vhurtevent** [comment]
New findings in this issue : https://github.com/kubernetes/cloud-provider-openstack/issues/2295

**Comment by Payback159** [comment]
@vhurtevent  has already pointed out in the previous comment that the problem is apparently solved in the cinder-csi-plugin. Only in the sense of a clean conclusion:

We were able to install the new version of the cinder-csi-plugin in our environment and can confirm that the log entries have also disappeared here.

In our larger clusters, this has also meant that pods with RWO volumes that have ended up on another node as a result of rescheduling can now mount their volume also more quickly.

Thank you very much @jsafrane and @vhurtevent !
