### ISSUE TITLE
Failed to list VolumentAttachment

### ISSUE THREAD

**Issue by ZhaokunQiu** [kubernetes-csi/external-attacher#44]
My kubernetes version:1.9.6
Installing tool: kubeadm
Troubles:
I'm testing with hostpath CSI driver as the example shows. The pod is running well:
`[root@node-1 ~]# kubectl get pods -o wide
`
`NAME         READY     STATUS              RESTARTS   AGE       IP              NODE
csi-pod          4/4           Running                       0          4h        172.17.0.3   node-1
`

And the pvc is created normally:
`[root@node-1 ~]# kubectl get pvc
`
`NAME      STATUS    VOLUME                CAPACITY   ACCESS MODES   STORAGECLASS      AGE
`
`csi-pvc      Bound     pvc-b694d42f-42cc-11e8-bc4f-525400b538e8   1Gi        RWO            csi-hostpath-sc   2h
`

`[root@node-1 ~]# kubectl get pv
`
`NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM             STORAGECLASS      REASON    AGE
`
`pvc-b694d42f-42cc-11e8-bc4f-525400b538e8   1Gi        RWO            Delete           Bound     default/csi-pvc   csi-hostpath-sc             2h
`

But when I create a pod to test the pvc, the pod is always ContainerCreating, and the external-attacher container of csi-pod logs:
`I0418 08:28:30.703166       1 reflector.go:240] Listing and watching *v1beta1.VolumeAttachment from github.com/kubernetes-csi/external-attacher/vendor/k8s.io/client-go/informers/factory.go:87
E0418 08:28:30.713445       1 reflector.go:205] github.com/kubernetes-csi/external-attacher/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource
`

And while getting the resource directly, here is the result:
`[root@node-1 ~]# kubectl get volumeattachments
`
`NAME                                                                   AGE
`
`csi-ad50ac36b76e55e8621e4f37e9d561bf141ed57cd6c1d5b8d0219fda62ab03cb   2h
`
Anyone has met the same problem?

**Comment by jsafrane** [comment]
external-attacher 0.2.0 now supports only Kubernetes 1.10 that added VolumeAttachment to storage.k8s.io/v1beta1 API.

@lpabon, should we build and tag 0.1 images for Kubernetes 1.9?

**Comment by ZhaokunQiu** [comment]
@jsafrane Ah, many thanks! So I will upgrade k8s version, or just adjust the external-attacher version to 0.10?

**Comment by ZhaokunQiu** [comment]
It seems that there isn't  v0.1.0 in the repo?

**Comment by jsafrane** [comment]
I think we weren't tagging our 0.1.0 containers, we used `latest` only at that time. 

I'd recommend upgrading Kubernetes to 1.10 and it should start working with 0.2.0 images we have now.

**Comment by ZhaokunQiu** [comment]
@jsafrane Solved it! Thanks a lot!

**Comment by jsafrane** [comment]
I am glad to help. Please post any other issues or even PRs with updated documentation :-)
