### ISSUE TITLE
Readme has incorrect compatibility information for kubernetes version

### ISSUE THREAD

**Issue by karthichu** [kubernetes-csi/external-attacher#458]
## Compatibility

This information reflects the head of this branch.

| Compatible with CSI Version                                                                | Container Image                     | [Min K8s Version](https://kubernetes-csi.github.io/docs/kubernetes-compatibility.html#minimum-version) | [Recommended K8s Version](https://kubernetes-csi.github.io/docs/kubernetes-compatibility.html#recommended-version) |
| ------------------------------------------------------------------------------------------ | -----------------------------------------| ---- | ---- |
| [CSI Spec v1.5.0](https://github.com/container-storage-interface/spec/releases/tag/v1.5.0) | registry.k8s.io/sig-storage/csi-attacher | 1.17 | 1.22 |

**Comment by jsafrane** [comment]
@karthichu what information is wrong there and what would be the correct one? A PR might help here.
