### ISSUE TITLE
`fault.CnsNotRegisteredFault.summary` while consuming a volume by a pod

### ISSUE THREAD

**Issue by viveksinghggits** [kubernetes-csi/external-attacher#460]
I have a use case where I am trying to copy the PVC and it's respective PV resource from one namespace to another namespace pointing to the same underlying `volumeHandle`. Once the PV and PVCs are copied over we delete the original PVC and PV pair.
The PV and PVC are being copied over successfully but when a pod tries to consume that PVC below is the error that we see in the events
```
  Warning  FailedAttachVolume  3m                     attachdetach-controller  AttachVolume.Attach failed for volume "pvc-ee6cab64-7e07-4096-a0f3-217fd1841fac-somethingelse" : rpc error: code = Internal desc = failed to attach disk: "03b797b0-f3f5-443a-8773-2ba105a54a17" with node: "vsphere-abc-staging-30-md-0-b47c794f-8qjcp" err failed to attach cns volume: "03b797b0-f3f5-443a-8773-2ba105a54a17" to node vm: "VirtualMachine:vm-7043 [VirtualCenterHost: a.b.c.d, UUID: 42205db2-e106-464a-1efa-ba82ffd8479a, Datacenter: Datacenter [Datacenter: Datacenter:datacenter-3, VirtualCenterHost: a.b.c.d]]". fault: "(*types.LocalizedMethodFault)(0xc015040040)({\n DynamicData: (types.DynamicData) {\n },\n Fault: (types.BaseMethodFault) <nil>,\n LocalizedMessage: (string) (len=35) \"fault.CnsNotRegisteredFault.summary\"\n})\n". opId: "d27d6db1"
```

We don't see any helpful error messages in the csi controller plugin logs but we do see the exact above error message in the kube controller logs.
So, I have tow main questions
1. Is it even a good idea to copy the volume using the way that is described above
2. Has someone encountered this error before and has some pointers on what can be done about it.

Another interesting thing that we have observed is, if we don't delete the original PVC/PV pair we don't see this problem.

**Comment by viveksinghggits** [comment]
This is reproducible just on VMWare vSphere clusters.

**Comment by jsafrane** [comment]
This looks like an issue with vSphere CSI driver, please report the bug at https://github.com/kubernetes-sigs/vsphere-csi-driver

/close
