### ISSUE TITLE
CSI attacher: Does version 2.2.1 have an ARM architecture? What is the download address? Thank you

### ISSUE THREAD

**Issue by shirongsheng** [kubernetes-csi/external-attacher#551]
CSI attacher: Does version 2.2.1 have an ARM architecture? What is the download address? Thank you

**Comment by jsafrane** [comment]
I don't think we build ARM images, at least those on `registry.k8s.io/sig-storage/csi-attacher:v4.5.1` look amd64 only.
We're open for improvements. "Someone" needs to investigate how to build + push + promote images for other architectures and update our Makefiles. Note that all CSI sidecars share the same Makefile from https://github.com/kubernetes-csi/csi-release-tools and any investigation / fix must start there.

/help
