### ISSUE TITLE
Upgrade external-attacher to use Debian 12 Distroless

### ISSUE THREAD

**Issue by jhawkins1** [kubernetes-csi/external-attacher#558]
Since Debian 12 Distroless is available, as well as, the latest releases of Kubernetes and many of the Kubernetes related projects have moved to Debian 12, we would request that external-attacher move to Debian 12 Distroless to align with other Kubernetes components.

Benefits: Alignment of the Container OS being used to other Kubernetes Components and related Projects. Reduces fan-out of multiple OSes or different versions of OSes across components. Potential benefits as to being able to obtain OS patches for vulnerabilities where Debian has decided only to fix in latest LTS (Debian 12) release and not older LTS releases.

**Comment by jsafrane** [comment]
Sure, feel free to update our Dockerfiles, but please do so in all repos in https://github.com/kubernetes-csi so they're consistent. Beware, some of them are not distroless.

**Comment by sdx-jkataja** [comment]
It appears the `gcr.io/distroless/static:latest base image` has already changed to Debian 12.
The change has taken place some time in between the versions:

 - v4.5.1 is based on Debian 11
 - v4.6.0 is based on Debian 12

**Comment by jsafrane** [comment]
/close
v4.6.0 is based on Debian 12
