### ISSUE TITLE
call Probe error due to timeout setting is too short

### ISSUE THREAD

**Issue by wnxn** [kubernetes-csi/external-attacher#67]
Hi,
1. I develop a CSI driver and implement Probe call. The Probe call verifies driver status and takes about 2 seconds. The external attacher prints calling Probe RPC timeout log (`Probe failed with rpc error: code = DeadlineExceeded desc = context deadline exceeded`). In my opinion, when external attacher calling Probe, the timeout setting is too short (only one second).  We can increase timeout second.
https://github.com/kubernetes-csi/external-attacher/blob/5a4cc3b1af15966cdb9b8ca1af6ab3adade877b0/cmd/csi-attacher/main.go#L198
2. We would not share the same context object in several GRPC call.
https://github.com/kubernetes-csi/external-attacher/blob/5a4cc3b1af15966cdb9b8ca1af6ab3adade877b0/cmd/csi-attacher/main.go#L101

**Comment by jsafrane** [comment]
fixed by #68
